name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Generate Demo
        run: yarn generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: playground/dist # The folder the action should deploy.
